name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: mahmoudfalous
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Create timestamp
        run: |
          sudo chmod -R 777 dist || true
          mkdir -p dist
          echo "Last snake run: $(date)" > dist/last_snakerun.txt

      # Push snake SVGs to output branch
      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: last_snakerun_$(date +'%Y-%m-%d_%H-%M-%S')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create contribution commit on main
      - name: Commit activity to main
        run: |
          git config --global user.name "Mahmoud Mohamed"
          git config --global user.email "mahmoudfalous@gmail.com"

          # Sync before editing
          git pull --rebase origin main

          echo "Snake run at $(date)" >> activity.log

          git add activity.log

          git commit -m "last_snakerun_$(date +'%Y-%m-%d_%H-%M-%S')" || exit 0

          git push origin main
