name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: mahmoudfalous
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Create timestamp file
        run: |
          sudo chmod -R 777 dist || true
          mkdir -p dist
          echo "Last snake run: $(date)" > dist/last_snakerun.txt

      - name: Commit files to main
        run: |
          git config --global user.name "Mahmoud Mohamed"
          git config --global user.email "mahmoudfalous@gmail.com"

          git add dist

          git commit -m "last_snakerun_$(date +'%Y-%m-%d_%H-%M-%S')" || exit 0

          git push
